export const mockCommunities = [
  {
    id: "1",
    title: "Tech Source Club",
    description: "A community for tech lovers to explore, learn, and connect.",
    creator: { name: "Harshita", avatar: "/placeholder.svg?height=40&width=40" },
    createdAt: "04 Jan, 2024",
    memberCount: 1100,
    postCount: 900,
    viewCount: 4300,
    members: [
      { avatar: "/placeholder.svg?height=32&width=32", name: "Alice" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Bob" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Charlie" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Diana" },
    ],
    cover: "/images/community-illustration.png",
    category: "Technology",
    isJoined: false,
    isTrending: true,
    isFeatured: true,
    privacy: "public" as const,
    features: ["events", "moderated", "chat"],
    location: "Global",
  },
  {
    id: "2",
    title: "Design Collective",
    description: "Where creativity meets functionality. Share your designs and get inspired.",
    creator: { name: "Sarah Chen", avatar: "/placeholder.svg?height=40&width=40" },
    createdAt: "15 Feb, 2024",
    memberCount: 890,
    postCount: 650,
    viewCount: 2800,
    members: [
      { avatar: "/placeholder.svg?height=32&width=32", name: "Eve" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Frank" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Grace" },
    ],
    cover: "/placeholder.svg?height=200&width=400",
    category: "Design",
    isJoined: true,
    isFeatured: true,
    privacy: "private" as const,
    features: ["resources", "networking"],
    location: "San Francisco",
  },
  {
    id: "3",
    title: "Startup Founders Hub",
    description: "Building the future together. Connect with fellow entrepreneurs.",
    creator: { name: "Mike Johnson", avatar: "/placeholder.svg?height=40&width=40" },
    createdAt: "20 Mar, 2024",
    memberCount: 567,
    postCount: 420,
    viewCount: 1900,
    members: [
      { avatar: "/placeholder.svg?height=32&width=32", name: "Henry" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Ivy" },
    ],
    cover: "/placeholder.svg?height=200&width=400",
    category: "Business",
    isJoined: false,
    isTrending: true,
    isCreatedByMe: true,
    privacy: "public" as const,
    features: ["networking", "mentorship"],
    location: "New York",
  },
  {
    id: "4",
    title: "Photography Masters",
    description: "Capture moments, share stories, and learn from the best photographers.",
    creator: { name: "Emma Wilson", avatar: "/placeholder.svg?height=40&width=40" },
    createdAt: "10 Apr, 2024",
    memberCount: 1250,
    postCount: 1100,
    viewCount: 5200,
    members: [
      { avatar: "/placeholder.svg?height=32&width=32", name: "Jack" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Kate" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Liam" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Mia" },
    ],
    cover: "/placeholder.svg?height=200&width=400",
    category: "Photography",
    isJoined: true,
    isTrending: true,
    isFeatured: true,
    privacy: "public" as const,
    features: ["events", "resources", "chat"],
    location: "Los Angeles",
  },
  {
    id: "5",
    title: "Fitness Warriors",
    description: "Transform your body and mind. Share workouts, nutrition tips, and motivation.",
    creator: { name: "Alex Rodriguez", avatar: "/placeholder.svg?height=40&width=40" },
    createdAt: "25 May, 2024",
    memberCount: 780,
    postCount: 340,
    viewCount: 2100,
    members: [
      { avatar: "/placeholder.svg?height=32&width=32", name: "Noah" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Olivia" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Paul" },
    ],
    cover: "/placeholder.svg?height=200&width=400",
    category: "Health",
    isJoined: false,
    isCreatedByMe: true,
    privacy: "public" as const,
    features: ["events", "networking"],
    location: "Miami",
  },
  {
    id: "6",
    title: "Book Club Central",
    description: "Discover new books, discuss your favorites, and connect with fellow readers.",
    creator: { name: "Lisa Thompson", avatar: "/placeholder.svg?height=40&width=40" },
    createdAt: "08 Jun, 2024",
    memberCount: 450,
    postCount: 280,
    viewCount: 1600,
    members: [
      { avatar: "/placeholder.svg?height=32&width=32", name: "Quinn" },
      { avatar: "/placeholder.svg?height=32&width=32", name: "Ruby" },
    ],
    cover: "/placeholder.svg?height=200&width=400",
    category: "Literature",
    isJoined: true,
    isFeatured: true,
    privacy: "private" as const,
    features: ["resources", "moderated"],
    location: "Boston",
  },
]
